[package]
name = "lobby-server"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
anyhow = "1"
